name: read_reveal_ai
description: A mobile app that allows users to capture book pages and get word explanations via Gemini API.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # UI
  cupertino_icons: ^1.0.6
  flutter_spinkit: ^5.2.0
  flutter_markdown: ^0.6.18
  url_launcher: ^6.2.4
  
  # Camera and Image
  image_picker: ^1.0.4
  camera: ^0.10.5+5
  path_provider: ^2.1.1
  path: ^1.8.3
  
  # API
  http: ^1.1.0
  
  # Storage
  flutter_secure_storage: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # State Management
  provider: ^6.0.5
  
  # Utils
  uuid: ^4.2.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/logo_RRA.png
    - assets/images/full_RRA.png

# Flutter icon configuration to be used with flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_RRA.png"
  min_sdk_android: 21
  remove_alpha_ios: true
